
var res = {
    bgmusic: "res/music/Happy_Mandolin.mp3",
    roomlistmusic: "res/music/Calypso_Beach_Walk.mp3",
    roommusic: "res/music/Splashing_Around.mp3",
    bag:"res/bag/bagbg.png",
    bg: "res/test5.jpg",
    helloBG_png: "res/helloBG.png",
    start_n_png: "res/start_n.png",
    start_s_png: "res/start_s.png",
    m1: "res/m1/m1.c3b",
    login_json: "res/MainScene.json",

    moneone_png: "res/animation/moneone.png",
    moneone_plist: "res/animation/moneone.plist",
    monetwo_png: "res/animation/monetwo.png",
    monetwo_plist: "res/animation/monetwo.plist",
    monethree_png: "res/animation/monethree.png",
    monethree_plist: "res/animation/monethree.plist",
    monefour_png: "res/animation/monefour.png",
    monefour_plist: "res/animation/monefour.plist",

    mtwoone_png: "res/animation/mtwoone.png",
    mtwoone_plist: "res/animation/mtwoone.plist",
    mtwotwo_png: "res/animation/mtwotwo.png",
    mtwotwo_plist: "res/animation/mtwotwo.plist",
    mtwothree_png: "res/animation/mtwothree.png",
    mtwothree_plist: "res/animation/mtwothree.plist",
    mtwofour_png: "res/animation/mtwofour.png",
    mtwofour_plist: "res/animation/mtwofour.plist",

    mthreeone_png: "res/animation/mthreeone.png",
    mthreeone_plist: "res/animation/mthreeone.plist",
    mthreetwo_png: "res/animation/mthreetwo.png",
    mthreetwo_plist: "res/animation/mthreetwo.plist",
    mthreethree_png: "res/animation/mthreethree.png",
    mthreethree_plist: "res/animation/mthreethree.plist",
    mthreeforur_png: "res/animation/mthreeforur.png",
    mthreeforur_plist: "res/animation/mthreeforur.plist",

    mfourone_png: "res/animation/mfourone.png",
    mfourone_plist: "res/animation/mfourone.plist",
    mfourtwo_png: "res/animation/mfourtwo.png",
    mfourtwo_plist: "res/animation/mfourtwo.plist",
    mfourthree_png: "res/animation/mfourthree.png",
    mfourthree_plist: "res/animation/mfourthree.plist",
    mfourfour_png: "res/animation/mfourfour.png",
    mfourfour_plist: "res/animation/mfourfour.plist",

    yes: "res/yes.png",
    no: "res/no.png",
    buy: "res/buy.png",

    Dice_plist: "res/animation/Dice.plist",
    Dice_png: "res/animation/Dice.png",
    Barrier_plist: "res/animation/Barrier.plist",
    Barrier_png: "res/animation/Barrier.png",
    equality_plist: "res/animation/equality.plist",
    equality_png: "res/animation/equality.png",
    FlyEag_plist: "res/animation/FlyEag.plist",
    FlyEag_png: "res/animation/FlyEag.png",
    NoHouse_plist: "res/animation/NoHouse.plist",
    NoHouse_png: "res/animation/NoHouse.png",
    NoMoney_plist: "res/animation/NoMoney.plist",
    NoMoney_png: "res/animation/NoMoney.png",
    Snow_plist: "res/animation/Snow.plist",
    Snow_png: "res/animation/Snow.png",
    AnyDoor_plist: "res/animation/AnyDoor.plist",
    AnyDoor_png: "res/animation/AnyDoor.png",
    tortoise_plist: "res/animation/tortoise.plist",
    tortoise_png: "res/animation/tortoise.png",
    exchange_plist: "res/animation/exchange.plist",
    exchange_png: "res/animation/exchange.png",
    shield_plist: "res/animation/shield.plist",
    shield_png: "res/animation/shield.png",
    bigrevolution_plist: "res/animation/bigrevolution.plist",
    bigrevolution_png: "res/animation/bigrevolution.png",
    buy_plist: "res/animation/buy.plist",
    buy_png: "res/animation/buy.png",
    fate_plist: "res/animation/fate.plist",
    fate_png: "res/animation/fate.png",
    fatec_plist: "res/animation/fatec.plist",
    fatec_png: "res/animation/fatec.png",

    png1: "res/Login/LI01.png",
    png2: "res/Login/LI02.png",
    png3: "res/Login/LI07.jpg",
    png4: "res/Login/BaS31.png",
    png5: "res/Login/BaS32.png",
    png6: "res/Login/Frd11.png",
    Login_json: "res/Login.json",
    level_selection_json: "res/Selection/LevelSelection.json",

    dicecard_json: "res/carduse/dicecard/MainScene.json",
    chooseplycard_json: "res/carduse/nomoney/MainScene.json",
    revolution_json: "res/carduse/bigrevolution/MainScene.json",
    landroad_json: "res/carduse/landroad/MainScene.json",
    road_json: "res/carduse/road/MainScene.json",
    roomlist_json: "res/gameroom/ouside/MainScene.json",
    room_json: "res/gameroom/in/MainScene.json",
    addroom_json: "res/gameroom/add/MainScene.json",

    moneonehi_png: "res/animation/moneonehi.png",
    moneonehi_plist: "res/animation/moneonehi.plist",
    monetwohi_png: "res/animation/monetwohi.png",
    monetwohi_plist: "res/animation/monetwohi.plist",
    monethreehi_png: "res/animation/monethreehi.png",
    monethreehi_plist: "res/animation/monethreehi.plist",
    monefourhi_png: "res/animation/monefourhi.png",
    monefourhi_plist: "res/animation/monefourhi.plist",

    mtwoonehi_png: "res/animation/mtwoonehi.png",
    mtwoonehi_plist: "res/animation/mtwoonehi.plist",
    mtwotwohi_png: "res/animation/mtwotwohi.png",
    mtwotwohi_plist: "res/animation/mtwotwohi.plist",
    mtwothreehi_png: "res/animation/mtwothreehi.png",
    mtwothreehi_plist: "res/animation/mtwothreehi.plist",
    mtwofourhi_png: "res/animation/mtwofourhi.png",
    mtwofourhi_plist: "res/animation/mtwofourhi.plist",

    mthreeonehi_png: "res/animation/mthreeonehi.png",
    mthreeonehi_plist: "res/animation/mthreeonehi.plist",
    mthreetwohi_png: "res/animation/mthreetwohi.png",
    mthreetwohi_plist: "res/animation/mthreetwohi.plist",
    mthreethreehi_png: "res/animation/mthreethreehi.png",
    mthreethreehi_plist: "res/animation/mthreethreehi.plist",
    mthreefourhi_png: "res/animation/mthreefourhi.png",
    mthreefourhi_plist: "res/animation/mthreefourhi.plist",

    mhouronehi_png: "res/animation/mhouronehi.png",
    mhouronehi_plist: "res/animation/mhouronehi.plist",
    mhourtwohi_png: "res/animation/mhourtwohi.png",
    mhourtwohi_plist: "res/animation/mhourtwohi.plist",
    mhourthreehi_png: "res/animation/mhourthreehi.png",
    mhourthreehi_plist: "res/animation/mhourthreehi.plist",
    mhourhourhi_png: "res/animation/mhourhourhi.png",
    mhourhourhi_plist: "res/animation/mhourhourhi.plist",

    moneonewin_png: "res/animation/moneonewin.png",
    moneonewin_plist: "res/animation/moneonewin.plist",
    monetwowin_png: "res/animation/monetwowin.png",
    monetwowin_plist: "res/animation/monetwowin.plist",
    monethreewin_png: "res/animation/monethreewin.png",
    monethreewin_plist: "res/animation/monethreewin.plist",
    monefourwin_png: "res/animation/monefourwin.png",
    monefourwin_plist: "res/animation/monefourwin.plist",

    mtwoonewin_png: "res/animation/mtwoonewin.png",
    mtwoonewin_plist: "res/animation/mtwoonewin.plist",
    mtwotwowin_png: "res/animation/mtwotwowin.png",
    mtwotwowin_plist: "res/animation/mtwotwowin.plist",
    mtwothreewin_png: "res/animation/mtwothreewin.png",
    mtwothreewin_plist: "res/animation/mtwothreewin.plist",
    mtwofourwin_png: "res/animation/mtwofourwin.png",
    mtwofourwin_plist: "res/animation/mtwofourwin.plist",

    mthreeonewin_png: "res/animation/mthreeonewin.png",
    mthreeonewin_plist: "res/animation/mthreeonewin.plist",
    mthreetwowin_png: "res/animation/mthreetwowin.png",
    mthreetwowin_plist: "res/animation/mthreetwowin.plist",
    mthreethreewin_png: "res/animation/mthreethreewin.png",
    mthreethreewin_plist: "res/animation/mthreethreewin.plist",
    mthreefourwin_png: "res/animation/mthreefourwin.png",
    mthreefourwin_plist: "res/animation/mthreefourwin.plist",

    mfouronewin_png: "res/animation/mfouronewin.png",
    mfouronewin_plist: "res/animation/mfouronewin.plist",
    mfourtwowin_png: "res/animation/mfourtwowin.png",
    mfourtwowin_plist: "res/animation/mfourtwowin.plist",
    mfourthreewin_png: "res/animation/mfourthreewin.png",
    mfourthreewin_plist: "res/animation/mfourthreewin.plist",
    mfourfourwin_png: "res/animation/mfourfourwin.png",
    mfourfourwin_plist: "res/animation/mfourfourwin.plist",

    moneonelose_png: "res/animation/moneonelose.png",
    moneonelose_plist: "res/animation/moneonelose.plist",
    monetwolose_png: "res/animation/monetwolose.png",
    monetwolose_plist: "res/animation/monetwolose.plist",
    monethreelose_png: "res/animation/monethreelose.png",
    monethreelose_plist: "res/animation/monethreelose.plist",
    monefourlose_png: "res/animation/monefourlose.png",
    monefourlose_plist: "res/animation/monefourlose.plist",

    mtwoonelose_png: "res/animation/mtwoonelose.png",
    mtwoonelose_plist: "res/animation/mtwoonelose.plist",
    mtwotwolose_png: "res/animation/mtwotwolose.png",
    mtwotwolose_plist: "res/animation/mtwotwolose.plist",
    mtwothreelose_png: "res/animation/mtwothreelose.png",
    mtwothreelose_plist: "res/animation/mtwothreelose.plist",
    mtwofourlose_png: "res/animation/mtwofourlose.png",
    mtwofourlose_plist: "res/animation/mtwofourlose.plist",

    mthreeonelose_png: "res/animation/mthreeonelose.png",
    mthreeonelose_plist: "res/animation/mthreeonelose.plist",
    mthreetwolose_png: "res/animation/mthreetwolose.png",
    mthreetwolose_plist: "res/animation/mthreetwolose.plist",
    mthreethreelose_png: "res/animation/mthreethreelose.png",
    mthreethreelose_plist: "res/animation/mthreethreelose.plist",
    mthreefourlose_png: "res/animation/mthreefourlose.png",
    mthreefourlose_plist: "res/animation/mthreefourlose.plist",

    mfouronelose_png: "res/animation/mfouronelose.png",
    mfouronelose_plist: "res/animation/mfouronelose.plist",
    mfourtwolose_png: "res/animation/mfourtwolose.png",
    mfourtwolose_plist: "res/animation/mfourtwolose.plist",
    mfourthreelose_png: "res/animation/mfourthreelose.png",
    mfourthreelose_plist: "res/animation/mfourthreelose.plist",
    mfourfourlose_png: "res/animation/mfourfourlose.png",
    mfourfourlose_plist: "res/animation/mfourfourlose.plist",
};
var g_resources = [
    res.bag,
    res.helloBG_png,
    res.start_n_png,
    res.start_s_png,
    res.bg,
    res.login_json,

    res.moneone_png,
    res.moneone_plist,
    res.monetwo_png,
    res.monetwo_plist,
    res.monethree_png,
    res.monethree_plist,
    res.monefour_png,
    res.monefour_plist,

    res.mtwoone_png,
    res.mtwoone_plist,
    res.mtwotwo_png,
    res.mtwotwo_plist,
    res.mtwothree_png,
    res.mtwothree_plist,
    res.mtwofour_png,
    res.mtwofour_plist,

    res.mthreeone_png,
    res.mthreeone_plist,
    res.mthreetwo_png,
    res.mthreetwo_plist,
    res.mthreethree_png,
    res.mthreethree_plist,
    res.mthreeforur_png,
    res.mthreeforur_plist,

    res.mfourone_png,
    res.mfourone_plist,
    res.mfourtwo_png,
    res.mfourtwo_plist,
    res.mfourthree_png,
    res.mfourthree_plist,
    res.mfourfour_png,
    res.mfourfour_plist,

    res.Dice_plist,
    res.Dice_png,
    res.Barrier_plist,
    res.Barrier_png,
    res.equality_plist,
    res.equality_png,
    res.FlyEag_plist,
    res.FlyEag_png,
    res.NoHouse_plist,
    res.NoHouse_png,
    res.NoMoney_plist,
    res.NoMoney_png,
    res.Snow_plist,
    res.Snow_png,
    res.AnyDoor_plist,
    res.AnyDoor_png,
    res.tortoise_plist,
    res.tortoise_png,
    res.exchange_plist,
    res.exchange_png,
    res.shield_plist,
    res.shield_png,
    res.buy_plist,
    res.buy_png,
    res.bigrevolution_plist,
    res.bigrevolution_png,
    res.fate_plist,
    res.fate_png,
    res.fatec_plist,
    res.fatec_png,

    res.png1,
    res.png2,
    res.png3,
    res.png4,
    res.png5,
    res.png6,
    res.Login_json,
    res.level_selection_json,

    res.dicecard_json,
    res.chooseplycard_json,
    res.revolution_json,
    res.landroad_json,
    res.road_json,
    res.roomlist_json,
    res.room_json,
    res.addroom_json,

    res.moneonehi_png,
    res.moneonehi_plist,
    res.monetwohi_png,
    res.monetwohi_plist,
    res.monethreehi_png,
    res.monethreehi_plist,
    res.monefourhi_png,
    res.monefourhi_plist,

    res.mtwoonehi_png,
    res.mtwoonehi_plist,
    res.mtwotwohi_png,
    res.mtwotwohi_plist,
    res.mtwothreehi_png,
    res.mtwothreehi_plist,
    res.mtwofourhi_png,
    res.mtwofourhi_plist,

    res.mthreeonehi_png,
    res.mthreeonehi_plist,
    res.mthreetwohi_png,
    res.mthreetwohi_plist,
    res.mthreethreehi_png,
    res.mthreethreehi_plist,
    res.mthreefourhi_png,
    res.mthreefourhi_plist,

    res.mhouronehi_png,
    res.mhouronehi_plist,
    res.mhourtwohi_png,
    res.mhourtwohi_plist,
    res.mhourthreehi_png,
    res.mhourthreehi_plist,
    res.mhourhourhi_png,
    res.mhourhourhi_plist,

    res.moneonewin_png,
    res.moneonewin_plist,
    res.monetwowin_png,
    res.monetwowin_plist,
    res.monethreewin_png,
    res.monethreewin_plist,
    res.monefourwin_png,
    res.monefourwin_plist,

    res.mtwoonewin_png,
    res.mtwoonewin_plist,
    res.mtwotwowin_png,
    res.mtwotwowin_plist,
    res.mtwothreewin_png,
    res.mtwothreewin_plist,
    res.mtwofourwin_png,
    res.mtwofourwin_plist,

    res.mthreeonewin_png,
    res.mthreeonewin_plist,
    res.mthreetwowin_png,
    res.mthreetwowin_plist,
    res.mthreethreewin_png,
    res.mthreethreewin_plist,
    res.mthreefourwin_png,
    res.mthreefourwin_plist,

    res.mfouronewin_png,
    res.mfouronewin_plist,
    res.mfourtwowin_png,
    res.mfourtwowin_plist,
    res.mfourthreewin_png,
    res.mfourthreewin_plist,
    res.mfourfourwin_png,
    res.mfourfourwin_plist,

    res.moneonelose_png,
    res.moneonelose_plist,
    res.monetwolose_png,
    res.monetwolose_plist,
    res.monethreelose_png,
    res.monethreelose_plist,
    res.monefourlose_png,
    res.monefourlose_plist,

    res.mtwoonelose_png,
    res.mtwoonelose_plist,
    res.mtwotwolose_png,
    res.mtwotwolose_plist,
    res.mtwothreelose_png,
    res.mtwothreelose_plist,
    res.mtwofourlose_png,
    res.mtwofourlose_plist,

    res.mthreeonelose_png,
    res.mthreeonelose_plist,
    res.mthreetwolose_png,
    res.mthreetwolose_plist,
    res.mthreethreelose_png,
    res.mthreethreelose_plist,
    res.mthreefourlose_png,
    res.mthreefourlose_plist,

    res.mfouronelose_png,
    res.mfouronelose_plist,
    res.mfourtwolose_png,
    res.mfourtwolose_plist,
    res.mfourthreelose_png,
    res.mfourthreelose_plist,
    res.mfourfourlose_png,
    res.mfourfourlose_plist,
];
/*var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}*/

